### PR TITLE
Add dropdown/select element

### PR DESCRIPTION
**Pull request by brandones**

### CODE REVIEW

**Comment by jonathandick** [comment]
Can you include picture?

**Comment by brandones** [comment]
screenshot--2020-04-07--125545

Inspired by the outlined input (it's the same height, anyway)

Screenshot from 2020-04-07 12-56-48

**Comment by jonathandick** [comment]
Just to clarify, is this a single-select only? Do you intend to user for multi-select as well?

**Comment by brandones** [comment]
Yeah, just for single-select. No idea what we're doing for multi-select.

**Pull request merged**
